spring:
  profiles:
    active: core
  # 配置邮件
  mail:
    host: smtp.163.com
    username: nebulamooc@163.com
    password: mooc123456
    default-encoding: UTF-8
    port: 465 # 一般服务器的25端口会被禁用导致无法连接邮件服务器
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  redis:
    database: 1  # 使用索引为1的数据库作为缓存

port:
  http: 80
  https: 443

server:
  #ssl的端口
  port: ${port.http}

# FastDFS配置
fdfs:
  connectTimeout: 10  # 秒为单位
  networkTimeout: 30  # 秒为单位
  charset: UTF-8
  # 可填写多个，以逗号分隔
  trackerServerAddress: ${fastdfs_ip}:22122

# 执行器配置
executor:
  corePoolSize: 1
  maxPoolSize: 4
  keepAliveSeconds: 60
  awaitTerminationSeconds: 30
#jdbc
datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: Ding961122

