spring:
  profiles:
    active: core

websocket:
  port: 9080
  path: /websocket

tcp:
  backlog: 1024
  keepalive: true
  noDelay: true


ssl:
  certpath: nebulamooc.pem
  keypath: nebulamooc.key

port:
  http: 8081
  https: 8443

server:
  port: ${port.http}


